### ISSUE TITLE
Tailwind CSS not working 

### ISSUE THREAD

**Issue by OAtulA** [OAtulA/React-Router-basic#1]
I have Installed Tailwind CSS on my local system for my Vite React project.
I have followed the installation guidance from vite documentation.

But it isn't working.

I mean when I include the classes that doesn't work.

I tried modifying `postcss.config.js` , `src/index.css` , `tailwind.config.js` .
But it doesn't take effect 😕.

https://github.com/OAtulA/React-Router-basic

**Comment by NasifAhmed** [comment]
Cloned and tested it. Everything works. I think the problem is on your editor or browser.

**Comment by OAtulA** [comment]
Yeah it's fine It was just a typo
